#!/usr/bin/env python3
"""
Build a curated seed list of 365 neurosurgery/neurology practice topics
for one-topic-per-day daily uploads (day 1 = 2026-10-02 PKT / Asia/Karachi).

This module only generates the seed calendar. Grok authenticity polishing
is handled by grok_authenticate_calendar.py.
"""

from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path

# Day 1 of the upload calendar
ANCHOR_DATE = date(2026, 10, 2)
CALENDAR_ID = "neurosurgery-365-v1"
DATING_NOTE = (
    "Day 1 = 2026-10-02 (PKT / Asia/Karachi calendar date). "
    "Day N maps to ANCHOR_DATE + (N-1) days through 2027-10-01. "
    "Exactly ONE topic per day; daily pipeline publishes ONE digest/upload."
)

# (domain, topic, news_angle, search_keywords, practice_relevance)
# Balanced across real neurosurgical + neurological practice.
SEEDS: list[tuple[str, str, str, str, str]] = [
    # ---- Brain tumors / surgical neuro-oncology (1-45) ----
    ("Brain tumors", "Glioblastoma extent of resection and survival",
     "Digest recent evidence on maximal safe resection, 5-ALA/fluorescence, and survival endpoints in GBM.",
     "glioblastoma resection 5-ALA survival neurosurgery",
     "Guides how aggressively to pursue tumor cytoreduction while protecting function."),
    ("Brain tumors", "IDH-mutant glioma surgical timing",
     "Summarize research on when to operate early vs observe low-grade IDH-mutant gliomas.",
     "IDH mutant glioma surgery timing low grade",
     "Affects counseling of young adults with seizures and slow-growing lesions."),
    ("Brain tumors", "Awake craniotomy language mapping updates",
     "Cover advances in awake language/motor mapping protocols and outcome metrics.",
     "awake craniotomy language mapping glioma",
     "Improves eloquence preservation in dominant-hemisphere tumor surgery."),
    ("Brain tumors", "Meningioma Simpson grade in the MRI era",
     "Review whether Simpson grading still predicts recurrence with modern imaging follow-up.",
     "meningioma Simpson grade recurrence MRI",
     "Sets expectations for residual tumor and surveillance intervals."),
    ("Brain tumors", "Convexity vs skull-base meningioma decision trees",
     "Contrast surgical vs radiosurgical pathways for common meningioma locations.",
     "skull base meningioma radiosurgery vs resection",
     "Helps choose the least morbid durable control strategy."),
    ("Brain tumors", "Brain metastases: surgery vs SRS selection",
     "Digest guidelines on resection vs stereotactic radiosurgery for oligometastases.",
     "brain metastases surgery SRS oligometastatic",
     "Common MDT decision with immediate quality-of-life impact."),
    ("Brain tumors", "Leptomeningeal disease neurosurgical roles",
     "Outline limited but real roles of CSF diversion and biopsy in LMD care.",
     "leptomeningeal disease VP shunt biopsy neuro-oncology",
     "Clarifies when neurosurgery helps vs when systemic/IT therapy dominates."),
    ("Brain tumors", "Pituitary adenoma endoscopic endonasal outcomes",
     "Summarize remission and complication rates for endoscopic TSA in functional adenomas.",
     "endoscopic endonasal pituitary adenoma remission",
     "Core skull-base skill set for hormone-secreting and non-functioning tumors."),
    ("Brain tumors", "Cushing disease: remission after TSA",
     "Cover biochemical remission criteria and reoperation/radiosurgery salvage.",
     "Cushing disease transsphenoidal remission cortisol",
     "Avoids undertreating occult residual disease and adrenal crises."),
    ("Brain tumors", "Acromegaly surgical remission markers",
     "Review IGF-1/GH criteria and when to escalate to medical therapy or SRS.",
     "acromegaly surgery IGF-1 GH remission",
     "Impacts cardiometabolic risk reduction after GH-secreting adenoma surgery."),
    ("Brain tumors", "Craniopharyngioma hypothalamic-sparing strategies",
     "Digest surgical aggressiveness vs quality-of-life trade-offs near hypothalamus.",
     "craniopharyngioma hypothalamic sparing quality of life",
     "Critical in pediatric and young-adult endocrine/obesity outcomes."),
    ("Brain tumors", "Vestibular schwannoma: wait-scan vs intervene",
     "Compare observation, microsurgery, and SRS hearing/facial outcomes.",
     "vestibular schwannoma observation SRS hearing preservation",
     "Daily counseling topic for incidental CPA lesions."),
    ("Brain tumors", "Insular glioma approach corridors",
     "Summarize transsylvian vs transcortical approaches and morbidity data.",
     "insular glioma transsylvian approach morbidity",
     "High-risk eloquence region needing disciplined case selection."),
    ("Brain tumors", "Intraoperative MRI and ultrasound for glioma",
     "Cover evidence that iMRI/IOUS improve EOR without excess morbidity.",
     "intraoperative MRI ultrasound glioma extent resection",
     "Guides OR technology investment and case planning."),
    ("Brain tumors", "Fluorescence-guided resection beyond 5-ALA",
     "Digest fluorescein/NIR probes and trial status relative to 5-ALA.",
     "fluorescein NIR fluorescence guided neurosurgery",
     "Expands options where 5-ALA access is limited."),
    ("Brain tumors", "Primary CNS lymphoma: biopsy first principles",
     "Reinforce steroid timing, biopsy technique, and when resection is harmful.",
     "PCNSL biopsy steroids neurosurgery diagnosis",
     "Prevents mismanagement that delays chemoimmunotherapy."),
    ("Brain tumors", "Pineal region tumor biopsy vs resection",
     "Outline germ-cell workup, endoscopic biopsy, and open resection indications.",
     "pineal tumor endoscopic biopsy germ cell markers",
     "Avoids unnecessary open surgery when markers/histology dictate chemo/RT."),
    ("Brain tumors", "Intraventricular tumors and hydrocephalus",
     "Cover Colloid cyst, central neurocytoma, and ependymoma surgical priorities.",
     "colloid cyst neurocytoma intraventricular tumor surgery",
     "Acute obstruction risk makes timely surgery life-saving."),
    ("Brain tumors", "Recurrent GBM reoperation criteria",
     "Summarize when re-resection adds value versus bevacizumab/trial enrollment.",
     "recurrent glioblastoma reoperation criteria",
     "Balances hope, morbidity, and realistic survival gain."),
    ("Brain tumors", "Molecular neuropathology for the operating surgeon",
     "Translate WHO CNS5 practical takeaways surgeons must order and understand.",
     "WHO CNS5 molecular neuropathology glioma meningioma",
     "Ensures correct adjuvant pathway after surgery."),
    ("Brain tumors", "Laser interstitial thermal therapy (LITT) for tumors",
     "Review LITT indications for deep/recurrent lesions and evidence quality.",
     "LITT laser interstitial thermal therapy brain tumor",
     "Minimally invasive option when open surgery is high-risk."),
    ("Brain tumors", "Intraoperative neuromonitoring in tumor surgery",
     "Digest MEP/SSEP/mapping thresholds that change surgical stop points.",
     "intraoperative neuromonitoring MEP SSEP tumor surgery",
     "Protects motor pathways during aggressive cytoreduction."),
    ("Brain tumors", "Hemangioblastoma and VHL counseling",
     "Cover resection timing, residual disease, and systemic screening duties.",
     "hemangioblastoma VHL neurosurgery screening",
     "Links CNS surgery to lifelong multi-organ surveillance."),
    ("Brain tumors", "Chordoma and chondrosarcoma skull base",
     "Summarize en-bloc principles, margins, and particle therapy adjuncts.",
     "clival chordoma chondrosarcoma skull base surgery",
     "Rare but morbidity-defining lesions needing referral pathways."),
    ("Brain tumors", "Metastatic spine vs intracranial MDT sequencing",
     "Frame coordinated care when patients harbor both brain and spine mets.",
     "brain spine metastases multidisciplinary sequencing",
     "Prevents conflicting OR priorities and delayed RT."),
    ("Brain tumors", "Seizure control after glioma resection",
     "Cover AEDs, ECOG, and how EOR affects epilepsy outcomes in glioma.",
     "glioma surgery seizure control antiepileptic",
     "Seizure freedom often matters as much as survival to patients."),
    ("Brain tumors", "Elderly GBM: surgery vs biopsy-first",
     "Digest frailty-adapted strategies and hypofractionated RT pathways.",
     "elderly glioblastoma surgery frailty hypofractionation",
     "Avoids overtreatment in limited-life-expectancy cohorts."),
    ("Brain tumors", "Optic pathway glioma observation thresholds",
     "Pediatric/young adult decision points for surgery vs chemo/observe.",
     "optic pathway glioma observation chemotherapy surgery",
     "Vision preservation is the primary outcome metric."),
    ("Brain tumors", "Dural-based mets mimicking meningioma",
     "Highlight imaging red flags and biopsy/resection decision points.",
     "dural metastasis vs meningioma MRI neurosurgery",
     "Prevents wrong histopathology assumptions and wrong adjuvant plan."),
    ("Brain tumors", "Thalamic glioma biopsy strategies",
     "Compare stereotactic vs endoscopic corridors and complication rates.",
     "thalamic glioma stereotactic biopsy endoscopy",
     "Tissue diagnosis enables targeted therapy without open devastation."),
    ("Brain tumors", "Cerebellar metastasis surgical indications",
     "Cover mass-effect thresholds and hydrocephalus risk before SRS alone.",
     "cerebellar metastasis surgery hydrocephalus SRS",
     "Posterior fossa swelling can kill faster than cerebral lesions."),
    ("Brain tumors", "Tubular/minimally invasive tumor corridors",
     "Review evidence for tubular retractors in deep lesions.",
     "tubular retractor minimally invasive brain tumor",
     "May reduce retraction injury in selected deep tumors."),
    ("Brain tumors", "Second-look surgery after neoadjuvant therapy",
     "Emerging paradigms where systemic therapy precedes re-resection.",
     "neoadjuvant therapy second look neurosurgery glioma",
     "Shifts OR timing in molecularly selected patients."),
    ("Brain tumors", "Intraoperative frozen section limits",
     "When frozen is enough vs when molecular wait changes postop plan.",
     "intraoperative frozen section brain tumor accuracy",
     "Sets realistic expectations for intraoperative histology."),
    ("Brain tumors", "Radiation necrosis vs recurrence imaging",
     "Practical PET/perfusion/MRS algorithms before reoperation.",
     "radiation necrosis vs tumor recurrence PET perfusion",
     "Stops unnecessary reops for treatment effect."),
    ("Brain tumors", "Venous sinus meningioma reconstruction",
     "Cover sinus sacrifice vs reconstruction evidence and stroke risk.",
     "parasagittal meningioma sinus reconstruction",
     "Major morbidity driver in midline meningioma surgery."),
    ("Brain tumors", "Brainstem cavernoma surgery thresholds",
     "Hemorrhage risk vs surgical morbidity decision framework.",
     "brainstem cavernoma surgery hemorrhage risk",
     "High-stakes elective decision needing shared consent."),
    ("Brain tumors", "Incidentaloma counseling ethics",
     "PMDC-safe communication for asymptomatic MRI-found lesions.",
     "incidental brain lesion counseling shared decision",
     "Reduces anxiety and unnecessary surgery for benign findings."),
    ("Brain tumors", "Neurocognitive outcomes after tumor surgery",
     "Digest prehab/rehab cognition metrics tied to surgical corridors.",
     "neurocognitive outcome glioma surgery rehabilitation",
     "Return-to-work and family roles depend on cognition sparing."),
    ("Brain tumors", "Pediatric medulloblastoma risk stratification",
     "Surgical residual, molecular groups, and CSI implications.",
     "medulloblastoma molecular subgroup residual tumor",
     "Surgeon residual disease status still changes risk group."),
    ("Brain tumors", "Ependymoma: gross-total resection imperative",
     "Why GTR remains central across molecular subtypes.",
     "ependymoma gross total resection outcomes",
     "Incomplete resection often forces heavier adjuvant burden."),
    ("Brain tumors", "Primary spinal cord tumors surgical pearls",
     "Astrocytoma vs ependymoma dissection planes and outcomes.",
     "intramedullary spinal cord tumor ependymoma surgery",
     "Motor outcomes hinge on plane recognition and IONM."),
    ("Brain tumors", "Carcinomatous meningitis shunt infection risk",
     "When VP shunt is justified despite infection/seeding concerns.",
     "leptomeningeal carcinomatosis VP shunt infection",
     "Palliation of ICP vs infective complications trade-off."),
    ("Brain tumors", "Tumor-related epilepsy surgery adjuncts",
     "ECoG-guided resection margins beyond MRI-visible tumor.",
     "tumor related epilepsy ECoG guided resection",
     "Improves seizure freedom without abandoning oncologic goals."),
    ("Brain tumors", "Day-case / ERAS pathways in cranial oncology",
     "Evidence for enhanced recovery after selected craniotomies.",
     "ERAS craniotomy brain tumor length of stay",
     "Safer throughput and fewer complications in fit patients."),

    # ---- Cerebrovascular (46-90) ----
    ("Cerebrovascular", "Unruptured aneurysm GROW2 / PHASES counseling",
     "Translate modern risk scores into shared decisions for UIAs.",
     "unruptured intracranial aneurysm PHASES GROW2",
     "Prevents overtreatment of low-risk aneurysms and undertreatment of high-risk."),
    ("Cerebrovascular", "ISAT/BRAT legacy vs flow diversion era",
     "Update ruptured aneurysm modality choice with contemporary devices.",
     "ruptured aneurysm coiling clipping flow diversion",
     "Modality choice still drives durable occlusion and rebleed risk."),
    ("Cerebrovascular", "Aneurysmal SAH antifibrinolytic timing",
     "Digest ultra-early TXA evidence and current guideline stance.",
     "SAH tranexamic acid ultra early rebleeding",
     "May reduce ultra-early rebleed if used in the right window."),
    ("Cerebrovascular", "Delayed cerebral ischemia after SAH",
     "Cover multimodal DCI detection beyond classic vasospasm dogma.",
     "delayed cerebral ischemia SAH multimodal monitoring",
     "Leading cause of secondary injury after aneurysm securement."),
    ("Cerebrovascular", "Flow diverters for complex aneurysms",
     "Summarize occlusion rates, dual antiplatelet needs, and rupture caveats.",
     "flow diversion aneurysm dual antiplatelet",
     "Expands treatability of blister/fusiform lesions with medical trade-offs."),
    ("Cerebrovascular", "WEB / intrasaccular devices update",
     "Review wide-neck bifurcation aneurysm device outcomes.",
     "WEB device bifurcation aneurysm outcomes",
     "Offers endovascular option when coiling alone is unstable."),
    ("Cerebrovascular", "AVM ARUBA aftermath and case selection",
     "Revisit unruptured AVM treatment after ARUBA with modern data.",
     "AVM ARUBA unruptured treatment microsurgery embolization",
     "Stops reflexive treatment of low-grade AVMs and neglect of high-risk ones."),
    ("Cerebrovascular", "Spetzler-Martin grade surgical planning",
     "Practical SM/Lawton supplements for operative risk talk.",
     "Spetzler-Martin AVM grade surgical risk",
     "Standard language for MDT and patient consent."),
    ("Cerebrovascular", "Dural AVF Cognard/Borden management",
     "Cortical venous drainage as the intervention trigger.",
     "dural AV fistula Cognard Borden treatment",
     "Prevents hemorrhage from aggressive fistulas mistaken for benign tinnitus."),
    ("Cerebrovascular", "ICH surgical trial updates (ENRICH and beyond)",
     "Digest MIS evacuation vs medical care evidence for ICH.",
     "ICH ENRICH minimally invasive evacuation",
     "May reopen surgery for selected deep/lobar hemorrhages."),
    ("Cerebrovascular", "Posterior fossa ICH decompression thresholds",
     "Classic size/brainstem compression rules still saving lives.",
     "cerebellar hemorrhage surgical decompression threshold",
     "Time-critical decision distinct from supratentorial ICH."),
    ("Cerebrovascular", "EVT for large-core infarcts",
     "SELECT2/ANGEL-ASPECTS style evidence in plain language.",
     "endovascular thrombectomy large core ASPECTS",
     "Expands who still benefits from EVT despite large infarct."),
    ("Cerebrovascular", "Basilar artery occlusion EVT",
     "ATTENTION/BAOCHE takeaways for posterior circulation.",
     "basilar artery occlusion thrombectomy ATTENTION",
     "High-mortality stroke subtype with renewed interventional hope."),
    ("Cerebrovascular", "Carotid stenosis: CEA vs CAS vs TCAR",
     "Update symptomatic/asymptomatic thresholds and technique choice.",
     "carotid endarterectomy stenting TCAR symptomatic",
     "Stroke prevention surgery decisions in vascular MDT."),
    ("Cerebrovascular", "Moyamoya revascularization indications",
     "Direct vs indirect bypass evidence and stroke prevention.",
     "moyamoya bypass EDAS STA-MCA",
     "Prevents recurrent ischemia in progressive vasculopathy."),
    ("Cerebrovascular", "Cavernous malformation family counseling",
     "CCM genetics, hemorrhage risk, and surgery thresholds.",
     "cerebral cavernous malformation genetics hemorrhage",
     "Family planning and surveillance after first bleed."),
    ("Cerebrovascular", "Mycotic aneurysm management",
     "Antibiotic-first vs clip/coil in infective endocarditis context.",
     "mycotic aneurysm endocarditis neurosurgery",
     "Coordination with cardiology/ID prevents catastrophic rupture."),
    ("Cerebrovascular", "Blister aneurysm strategies",
     "Clip wrapping, trapping, and flow diversion options.",
     "blister aneurysm flow diversion clipping",
     "Fragile lesions with high intraoperative rupture risk."),
    ("Cerebrovascular", "Giant aneurysm bypass and trapping",
     "When parent-vessel sacrifice with bypass is required.",
     "giant aneurysm bypass trapping EC-IC",
     "Complex cerebrovascular surgery needing dedicated expertise."),
    ("Cerebrovascular", "Venous sinus thrombosis neurosurgical adjuncts",
     "Decompressive craniectomy indications in CVST with mass effect.",
     "CVST decompressive craniectomy venous thrombosis",
     "Last-resort salvage when medical therapy fails."),
    ("Cerebrovascular", "Perimesencephalic vs aneurysmal SAH workup",
     "Imaging algorithms that avoid missed aneurysms.",
     "perimesencephalic SAH CTA DSA workup",
     "Prevents false reassurance after non-aneurysmal-looking bleeds."),
    ("Cerebrovascular", "Antiplatelet management around aneurysm treatment",
     "Bridging and DAPT duration after stent/flow diverter.",
     "dual antiplatelet flow diverter aneurysm",
     "Balances thrombosis vs hemorrhagic complications."),
    ("Cerebrovascular", "Spinal AVMs and fistulas",
     "Foix-Alajouanine, DAVF myelopathy, and embolization/surgery roles.",
     "spinal dural AV fistula myelopathy treatment",
     "Treatable cause of progressive myelopathy if recognized."),
    ("Cerebrovascular", "Intraoperative aneurysm rupture drills",
     "Team checklist evidence and adenosine/temporary clip tactics.",
     "intraoperative aneurysm rupture management",
     "Crisis protocol that determines patient outcome in seconds."),
    ("Cerebrovascular", "Hunt-Hess / WFNS grading communication",
     "How grades guide family talks and ICU intensity.",
     "WFNS Hunt-Hess SAH grading prognosis",
     "Honest prognosis without abandoning salvageable poor-grades."),
    ("Cerebrovascular", "Blood pressure targets after EVT",
     "Post-recanalization BP evidence and hemorrhagic conversion risk.",
     "blood pressure after thrombectomy hemorrhagic conversion",
     "ICU detail that salvages hard-won reperfusion."),
    ("Cerebrovascular", "Secondary stroke prevention after aneurysm securement",
     "Statins, smoking cessation, and BP—neurosurgeon ownership.",
     "secondary prevention SAH aneurysm lifestyle",
     "Prevents next vascular event beyond the clipped/coiled sac."),
    ("Cerebrovascular", "Pediatric aneurysm peculiarities",
     "Etiology spectrum and treatment differences vs adults.",
     "pediatric intracranial aneurysm treatment",
     "Rare but needs different risk counseling."),
    ("Cerebrovascular", "Traumatic aneurysm after penetrating injury",
     "Screening timing and treatment after trauma.",
     "traumatic intracranial aneurysm penetrating injury",
     "Delayed bleeds after ballistic/stab trauma."),
    ("Cerebrovascular", "Reversible cerebral vasoconstriction pitfalls",
     "Distinguish RCVS from vasculitis/SAH before immunosuppression.",
     "RCVS thunderclap headache differential",
     "Avoids harmful treatment for a usually self-limited entity."),
    ("Cerebrovascular", "Subclavian steal and vertebral interventions",
     "When posterior circulation symptoms need vascular repair.",
     "subclavian steal vertebral artery stenosis",
     "Overlooked cause of vertebrobasilar ischemia."),
    ("Cerebrovascular", "Intracranial atherosclerosis angioplasty/stent",
     "SAMMPRIS lessons and modern device reappraisal.",
     "intracranial atherosclerosis stenting SAMMPRIS",
     "High-risk intracranial stenoses with limited endovascular wins."),
    ("Cerebrovascular", "Family screening after aneurysmal SAH",
     "Who to image among first-degree relatives.",
     "aneurysm family screening first degree relatives",
     "Practical prevention question families always ask."),
    ("Cerebrovascular", "Pregnancy and cerebrovascular emergencies",
     "SAH, CVST, and eclampsia-related ICH pathways.",
     "pregnancy SAH CVST intracranial hemorrhage",
     "Maternal-fetal dual responsibility in acute neurovascular care."),
    ("Cerebrovascular", "Tele-stroke networks for EVT triage",
     "How spoke-hub models change neurosurgical call patterns.",
     "telestroke thrombectomy hub spoke triage",
     "Determines who reaches the angio suite in time."),
    ("Cerebrovascular", "Hematoma expansion predictors in ICH",
     "Spot sign, anticoagulation reversal, BP control.",
     "ICH hematoma expansion spot sign reversal",
     "First hours decide whether surgery is even possible."),
    ("Cerebrovascular", "Middle meningeal artery embolization for cSDH",
     "Evidence for MMA embolization reducing recurrence.",
     "middle meningeal artery embolization chronic SDH",
     "Adjunct or alternative to repeat burr holes in elderly."),
    ("Cerebrovascular", "Chronic subdural: twist-drill vs burr-hole vs craniotomy",
     "Technique selection by membrane/architecture and frailty.",
     "chronic subdural hematoma burr hole recurrence",
     "Most common cranial emergency in aging populations."),
    ("Cerebrovascular", "Acute SDH surgical thresholds",
     "Thickness/midline shift rules and coagulopathy reversal.",
     "acute subdural hematoma surgical indications",
     "Classic trauma neuro decision with high stakes."),
    ("Cerebrovascular", "EDH: lucid interval and OR timing",
     "Why speed still beats perfection in epidural hematoma.",
     "epidural hematoma lucid interval surgery",
     "Teachable life-saving pattern recognition."),
    ("Cerebrovascular", "Hypertensive basal ganglia ICH medical first",
     "When NOT to operate and how to explain that to families.",
     "basal ganglia ICH medical management",
     "Most common ICH pattern needing honest non-operative counseling."),
    ("Cerebrovascular", "Anticoagulant-associated ICH reversal",
     "DOAC vs warfarin reversal updates for the on-call neurosurgeon.",
     "DOAC warfarin ICH reversal andexanet PCC",
     "Minutes matter before OR or ICU stabilization."),
    ("Cerebrovascular", "Vasospasm prophylaxis nimodipine adherence",
     "Practical barriers to completing nimodipine courses.",
     "nimodipine SAH vasospasm adherence",
     "Inexpensive intervention with proven outcome benefit."),
    ("Cerebrovascular", "External ventricular drain infection bundles",
     "Evidence-based EVD care to cut ventriculitis.",
     "EVD infection prevention bundle ventriculitis",
     "Device every cerebrovascular service depends on safely."),
    ("Cerebrovascular", "Cognitive outcomes after SAH",
     "Hidden disability despite 'good' mRS—rehab implications.",
     "SAH cognitive outcome rehabilitation mRS",
     "Patients look fine yet cannot return to work."),

    # ---- Spine (91-135) ----
    ("Spine", "Lumbar disc herniation: when to operate",
     "Update red flags, cauda equina, and failed conservative care timers.",
     "lumbar disc herniation discectomy indications cauda equina",
     "Most common elective spine decision in outpatient practice."),
    ("Spine", "Cauda equina syndrome time-to-decompress",
     "Evidence linking delay to permanent sphincter/sexual dysfunction.",
     "cauda equina syndrome emergency decompression timing",
     "Medicolegal and functional emergency every team must drill."),
    ("Spine", "Cervical myelopathy natural history",
     "Why progressive CSM usually needs surgery not endless PT.",
     "cervical spondylotic myelopathy natural history surgery",
     "Silent hand dysfunction progresses to irreversible cord injury."),
    ("Spine", "ACDF vs cervical disc arthroplasty",
     "Motion preservation evidence and adjacent segment disease.",
     "ACDF vs cervical disc replacement adjacent segment",
     "Choosing construct type for compatible cervical pathology."),
    ("Spine", "Laminoplasty vs laminectomy-fusion for CSM",
     "Posterior strategy selection by alignment and levels.",
     "cervical laminoplasty vs laminectomy fusion",
     "Multilevel myelopathy approach with kyphosis caveats."),
    ("Spine", "Lumbar stenosis MIS decompression",
     "Unilateral laminotomy bilateral decompression outcomes.",
     "lumbar stenosis minimally invasive decompression",
     "Relieves claudication with less soft-tissue trauma."),
    ("Spine", "Degenerative spondylolisthesis fusion debate",
     "SLIP / recent RCTs on decompression alone vs fusion.",
     "degenerative spondylolisthesis decompression vs fusion",
     "Avoids unnecessary fusion in stable slips."),
    ("Spine", "Adult spinal deformity alignment goals",
     "PI-LL, SVA, and frailty-adjusted correction targets.",
     "adult spinal deformity PI-LL SVA outcomes",
     "Overcorrection can be as harmful as undercorrection."),
    ("Spine", "Proximal junctional kyphosis prevention",
     "Tethers, cement, and soft landing strategies.",
     "proximal junctional kyphosis prevention deformity",
     "Major failure mode after long fusions."),
    ("Spine", "Thoracolumbar trauma AO classification surgery",
     "When A3/A4 and B/C injuries need fixation.",
     "thoracolumbar fracture AO Spine surgical indications",
     "Standardizes trauma spine decision language."),
    ("Spine", "Central cord syndrome surgical timing",
     "Early vs delayed decompression evidence in CCS.",
     "central cord syndrome early decompression",
     "Common incomplete SCI pattern in elderly hyperextension."),
    ("Spine", "Odontoid fracture elderly management",
     "Halo vs surgery vs collar—frailty first.",
     "odontoid fracture elderly surgery vs collar",
     "High-morbidity C2 injuries in osteoporotic patients."),
    ("Spine", "Hangman fracture operative criteria",
     "Stability assessment and C2-3 fusion indications.",
     "hangman fracture C2 surgery stability",
     "Classic upper cervical trauma pattern."),
    ("Spine", "Spinal epidural abscess urgency",
     "Red-flag infection needing drain + antibiotics.",
     "spinal epidural abscess surgery antibiotics",
     "Hours can separate full recovery from paraplegia."),
    ("Spine", "Pyogenic spondylodiscitis surgical indications",
     "Instability, abscess, and failed medical therapy triggers.",
     "spondylodiscitis surgical indications instability",
     "Rising incidence with diabetes and IV drug use."),
    ("Spine", "TB spine Hong Kong vs modern debridement",
     "Chemotherapy-first vs surgical debridement/fusion updates.",
     "spinal tuberculosis surgery chemotherapy Pakistan",
     "Highly relevant regional disease burden."),
    ("Spine", "Osteoporotic vertebral compression fractures",
     "Vertebroplasty/kyphoplasty evidence and patient selection.",
     "osteoporotic compression fracture vertebroplasty",
     "Painful fragility fractures in aging spine clinics."),
    ("Spine", "SI joint pain vs lumbar pathology",
     "Diagnostic injections and fusion evidence quality.",
     "sacroiliac joint fusion diagnostic injection",
     "Prevents wrong-level lumbar surgery for SI pain."),
    ("Spine", "Adjacent segment disease after fusion",
     "Prevention via motion preservation and level selection.",
     "adjacent segment disease lumbar fusion",
     "Long-term reoperation driver patients must understand."),
    ("Spine", "Spinal cord stimulation for FBSS",
     "When neuromodulation beats repeat fusion.",
     "spinal cord stimulation failed back surgery",
     "Functional option after exhausting structural fixes."),
    ("Spine", "Intraoperative neuromonitoring in deformity",
     "Alert algorithms that change screw trajectory or correction.",
     "IONM spinal deformity MEP alert response",
     "Protects cord during powerful corrective maneuvers."),
    ("Spine", "Pedicle screw navigation and robotics",
     "Accuracy gains vs cost and workflow evidence.",
     "robotic pedicle screw navigation accuracy",
     "Technology adoption decision for spine services."),
    ("Spine", "Endoscopic lumbar discectomy learning curve",
     "Outcomes parity with microdiscectomy when indicated.",
     "endoscopic lumbar discectomy vs microdiscectomy",
     "MIS option expanding in resource-variable settings."),
    ("Spine", "Cervical facet dislocation reduction",
     "Closed vs open reduction and timing of MRI.",
     "cervical facet dislocation reduction MRI timing",
     "Unstable injury with cord-at-risk decisions."),
    ("Spine", "Diffuse idiopathic skeletal hyperostosis trauma",
     "Why DISH spines fracture like ankylosed columns.",
     "DISH spine fracture surgical fixation",
     "Missed fractures in stiff spines cause delayed cord injury."),
    ("Spine", "Ankylosing spondylitis fracture care",
     "Long-segment fixation principles in AS trauma.",
     "ankylosing spondylitis spine fracture fixation",
     "Highly unstable injuries needing specialized fixation."),
    ("Spine", "Thoracic disc herniation rare but dangerous",
     "Anterior/posterolateral corridors and cord risk.",
     "thoracic disc herniation surgical approach",
     "Misdiagnosis as MS or malignancy delays care."),
    ("Spine", "Synovial cyst lumbar management",
     "Resection vs aspiration and instability assessment.",
     "lumbar synovial cyst surgery instability",
     "Treatable cause of radiculopathy/stenosis."),
    ("Spine", "Spinal meningioma posterior approach outcomes",
     "Simpson-like goals in intradural extramedullary tumors.",
     "spinal meningioma resection outcomes",
     "Excellent functional recovery if timely."),
    ("Spine", "Metastatic spinal cord compression MSCC",
     "SINS, NOMS, and RT vs surgery sequencing.",
     "metastatic spinal cord compression SINS NOMS",
     "Oncology emergency preserving ambulation."),
    ("Spine", "Primary spine bone tumors Enneking/WBB",
     "En-bloc thinking for chordoma/osteosarcoma of spine.",
     "spine chordoma en bloc resection WBB",
     "Rare cases needing referral to specialty centers."),
    ("Spine", "Postoperative spinal hematoma vigilance",
     "Risk factors and evacuate-now thresholds.",
     "postoperative spinal epidural hematoma evacuation",
     "Preventable cause of new postoperative deficit."),
    ("Spine", "Wound infection after instrumented fusion",
     "Retention vs removal algorithms and VAC use.",
     "spinal fusion surgical site infection management",
     "Saves constructs when infection is caught early."),
    ("Spine", "BMP and biologics in fusion",
     "Efficacy vs cancer/inflammation safety signals.",
     "BMP spinal fusion safety efficacy",
     "Adjunct choice with regulatory and cost implications."),
    ("Spine", "Opioid stewardship after spine surgery",
     "Multimodal analgesia pathways that cut chronic opioid use.",
     "opioid stewardship spine surgery multimodal analgesia",
     "Public-health and patient-safety priority."),
    ("Spine", "Return-to-work after lumbar discectomy",
     "Evidence-based timelines by job physical demand.",
     "return to work lumbar discectomy",
     "Practical counseling patients demand."),
    ("Spine", "Cervical radiculopathy non-op vs ACDF",
     "Natural history and epidural steroid evidence.",
     "cervical radiculopathy conservative vs surgery",
     "Most resolve without surgery if no myelopathy."),
    ("Spine", "Tarlov cysts: when to leave alone",
     "Intervention criteria vs incidental findings.",
     "Tarlov cyst surgery indications",
     "Stops unnecessary sacral surgery."),
    ("Spine", "Spinal arachnoid cyst / web myelopathy",
     "Imaging clues and fenestration outcomes.",
     "spinal arachnoid web cyst myelopathy surgery",
     "Under-recognized treatable myelopathy mimic."),
    ("Spine", "Pediatric scoliosis surgical timing",
     "Growth-friendly vs definitive fusion decision points.",
     "pediatric scoliosis surgery growing rods",
     "Balances curve control with pulmonary growth."),
    ("Spine", "Neuromuscular scoliosis perioperative risk",
     "Respiratory/nutrition optimization before long fusion.",
     "neuromuscular scoliosis surgery complications",
     "High-risk cohort needing multidisciplinary prep."),
    ("Spine", "Flatback syndrome revision strategies",
     "Pedicle subtraction osteotomy indications.",
     "flatback syndrome pedicle subtraction osteotomy",
     "Painful positive sagittal imbalance after prior fusion."),
    ("Spine", "Intraoperative vascular injury in lumbar surgery",
     "Prevention and salvage of great-vessel injury.",
     "lumbar surgery great vessel injury",
     "Rare catastrophic complication needing drills."),
    ("Spine", "Awake spine surgery under spinal anesthesia",
     "Selected lumbar MIS under regional anesthesia evidence.",
     "awake spine surgery spinal anesthesia",
     "Option for high-risk GA patients."),
    ("Spine", "Value-based spine care and unnecessary fusion",
     "Choosing wisely: when fusion lacks evidence.",
     "unnecessary spinal fusion choosing wisely",
     "Protects patients from low-value instrumentation."),

    # ---- Trauma TBI/SCI (136-165) ----
    ("Trauma", "Severe TBI ICP tiered management",
     "Tiered ICP protocols after BEST:TRIP / BOOTSTRAPs lessons.",
     "severe TBI ICP management tiered protocol",
     "Core ICU pathway for saving salvageable brains."),
    ("Trauma", "Decompressive craniectomy after RESCUEicp/DECRA",
     "When DC saves life vs worsens vegetative survival trade-offs.",
     "decompressive craniectomy RESCUEicp DECRA",
     "Family consent must include disability realities."),
    ("Trauma", "Mild TBI return-to-play / return-to-work",
     "Concussion protocols beyond rest dogma.",
     "mild TBI concussion return to play guidelines",
     "High-volume outpatient counseling topic."),
    ("Trauma", "Traumatic brain injury coagulopathy",
     "Viscoelastic testing and TXA CRASH-3 implications.",
     "TBI coagulopathy TXA CRASH-3",
     "Bleeding phenotype drives early mortality."),
    ("Trauma", "Pediatric TBI imaging rules",
     "PECARN-style avoidance of unnecessary CT radiation.",
     "pediatric TBI CT PECARN rules",
     "Protects children from radiation while catching surgical lesions."),
    ("Trauma", "Penetrating brain injury modern care",
     "Ballistics, vascular screening, and infection prophylaxis.",
     "penetrating brain injury management antibiotics CTA",
     "Conflict and civilian GSW patterns need protocols."),
    ("Trauma", "Blast TBI and polytrauma priorities",
     "Neurosurgery in damage-control sequence.",
     "blast traumatic brain injury damage control",
     "Relevant to regional mass-casualty preparedness."),
    ("Trauma", "Spinal cord injury ASIA grading",
     "Accurate exam that drives prognosis and trial eligibility.",
     "ASIA impairment scale spinal cord injury",
     "Shared language for SCI rehab and surgery."),
    ("Trauma", "Early decompressive surgery in SCI",
     "STASCIS-era timing evidence for traumatic SCI.",
     "early decompression spinal cord injury STASCIS",
     "Time-sensitive cord salvage."),
    ("Trauma", "Methylprednisolone in SCI: current stance",
     "Why routine NASCIS steroids fell out of favor.",
     "methylprednisolone spinal cord injury guidelines",
     "Stops harmful outdated steroid protocols."),
    ("Trauma", "Neurogenic shock vs hypovolemic shock",
     "Recognition and BP targets in acute SCI.",
     "neurogenic shock spinal cord injury MAP targets",
     "Misdiagnosis kills polytrauma patients."),
    ("Trauma", "Cranioplasty timing after DC",
     "Syndrome of the trephined and optimal windows.",
     "cranioplasty timing syndrome of the trephined",
     "Second surgery that restores CSF dynamics and cognition."),
    ("Trauma", "Post-traumatic hydrocephalus",
     "When ventriculomegaly after TBI needs a shunt.",
     "post traumatic hydrocephalus shunt indications",
     "Reversible cause of stalled rehab progress."),
    ("Trauma", "Chronic traumatic encephalopathy counseling",
     "Evidence limits and ethical sports counseling.",
     "chronic traumatic encephalopathy concussion counseling",
     "Media-hot topic needing scientific humility."),
    ("Trauma", "TBI tracheostomy and timing",
     "Airway decisions interacting with ICP and weaning.",
     "TBI tracheostomy timing ICP",
     "ICU logistics affecting infection and rehab start."),
    ("Trauma", "Venous thromboembolism prophylaxis in TBI",
     "When to start chemoprophylaxis after intracranial bleed.",
     "VTE prophylaxis traumatic brain injury timing",
     "Balances PE prevention vs hematoma expansion."),
    ("Trauma", "Seizure prophylaxis after severe TBI",
     "Early vs late PTE and AED duration evidence.",
     "post traumatic epilepsy prophylaxis phenytoit levetiracetam",
     "Prevents early seizures without endless AED exposure."),
    ("Trauma", "Hypothermia for TBI: trial takeaways",
     "Why prophylactic hypothermia failed and targeted uses remain.",
     "hypothermia traumatic brain injury trials",
     "Stops ineffective cooling protocols."),
    ("Trauma", "Multimodal neuromonitoring in TBI",
     "PbtO2, microdialysis adjuncts beyond ICP alone.",
     "PbtO2 microdialysis multimodal monitoring TBI",
     "Personalizes secondary injury prevention."),
    ("Trauma", "Gunshot spine injury surgical roles",
     "When to decompress/stabilize penetrating SCI.",
     "gunshot spinal cord injury surgery",
     "Civilian violence pattern needing clear algorithms."),
    ("Trauma", "Atlanto-occipital dissociation survival",
     "Recognition on CT and halo/ORIF pathways.",
     "atlanto-occipital dissociation diagnosis treatment",
     "Often fatal but occasionally salvageable if spotted."),
    ("Trauma", "Growing skull fracture in children",
     "Leptomeningeal cyst repair principles.",
     "growing skull fracture leptomeningeal cyst",
     "Delayed pediatric complication after linear fracture."),
    ("Trauma", "TBI rehabilitation early mobilization",
     "Evidence that early therapy improves outcomes.",
     "early mobilization TBI rehabilitation",
     "Neurosurgery handoff to rehab determines long-term function."),
    ("Trauma", "Disorders of consciousness prognosis",
     "CRS-R, imaging, and ethical goals-of-care talks.",
     "disorders of consciousness prognosis CRS-R",
     "Families need accurate vegetative vs MCS counseling."),
    ("Trauma", "Second impact syndrome awareness",
     "Rare but cited risk in repeated concussion.",
     "second impact syndrome concussion youth",
     "Youth sports counseling and sideline removal."),
    ("Trauma", "Trauma systems and neurosurgery coverage",
     "How transfer delays change SDH/EDH mortality.",
     "trauma system neurosurgery transfer delay",
     "System design is a clinical outcome variable."),
    ("Trauma", "Coagulopathic elderly ground-level falls",
     "Anticoagulant head injury observation protocols.",
     "elderly fall anticoagulant head injury CT",
     "High-volume ED neurosurgery consult pattern."),
    ("Trauma", "CSF leak after basilar skull fracture",
     "Conservative vs repair and meningitis prevention.",
     "basilar skull fracture CSF leak meningitis",
     "Classic trauma complication with infection risk."),
    ("Trauma", "Facial nerve injury in temporal bone trauma",
     "Steroids, exploration timing, and prognosis.",
     "temporal bone fracture facial nerve injury",
     "Otologic-neurosurgical crossover emergency."),
    ("Trauma", "SCI regenerative trials realistic outlook",
     "Stem cell/scaffold news literacy for patients.",
     "spinal cord injury stem cell trial evidence",
     "Protects patients from false-hope tourism."),

    # ---- Functional (166-195) ----
    ("Functional", "DBS for Parkinson disease patient selection",
     "EARLYSTIM lessons and levodopa challenge criteria.",
     "deep brain stimulation Parkinson EARLYSTIM",
     "Transforms motor fluctuation care when well selected."),
    ("Functional", "STN vs GPi DBS trade-offs",
     "Cognition, dyskinesia, and medication reduction differences.",
     "STN vs GPi deep brain stimulation",
     "Target choice personalizes risk/benefit."),
    ("Functional", "DBS for essential tremor",
     "Vim/PSA targeting and focused ultrasound alternatives.",
     "essential tremor DBS focused ultrasound",
     "Disabling tremor with durable surgical options."),
    ("Functional", "MR-guided focused ultrasound thalamotomy",
     "Incisionless tremor treatment evidence and limits.",
     "MRgFUS thalamotomy essential tremor",
     "Option when patients refuse implants."),
    ("Functional", "Epilepsy surgery after failed AEDs",
     "When to refer for Phase I/II evaluation.",
     "drug resistant epilepsy surgery referral",
     "Years of unnecessary seizures if referral delayed."),
    ("Functional", "Temporal lobectomy vs laser ablation",
     "Seizure freedom vs cognitive trade-offs in TLE.",
     "temporal lobectomy vs LITT epilepsy",
     "Gold-standard vs less invasive choices."),
    ("Functional", "SEE G guided neuromodulation for epilepsy",
     "Responsive neurostimulation and deep targets.",
     "RNS responsive neurostimulation epilepsy SEEG",
     "Options when resective surgery is unsafe."),
    ("Functional", "Vagus nerve stimulation practical outcomes",
     "Expectation setting for palliative epilepsy surgery.",
     "vagus nerve stimulation epilepsy outcomes",
     "Accessible neuromodulation in many regions."),
    ("Functional", "Hemispherectomy/hemispherotomy selection",
     "Catastrophic pediatric epilepsy surgical cure potential.",
     "hemispherotomy pediatric epilepsy",
     "Radical surgery with dramatic seizure benefits when indicated."),
    ("Functional", "Trigeminal neuralgia: MVD vs rhizotomy vs SRS",
     "First-line choice by age, vessels, and medical failure.",
     "trigeminal neuralgia MVD SRS rhizotomy",
     "Most painful condition with excellent surgical options."),
    ("Functional", "Glossopharyngeal neuralgia recognition",
     "Rare cranial neuralgia surgical strategies.",
     "glossopharyngeal neuralgia microvascular decompression",
     "Missed diagnosis leads to years of throat pain."),
    ("Functional", "Hemifacial spasm MVD outcomes",
     "Vessel decompression evidence and hearing risk.",
     "hemifacial spasm microvascular decompression",
     "QoL surgery with high success when vascular conflict found."),
    ("Functional", "Occipital nerve stimulation for headache",
     "Evidence quality in occipital neuralgia/chronic migraine.",
     "occipital nerve stimulation migraine neuralgia",
     "Functional option after failed medical headache care."),
    ("Functional", "Intrathecal drug delivery for spasticity/pain",
     "Baclofen/morphine pump candidacy and complications.",
     "intrathecal baclofen pump spasticity",
     "Tone and pain control when oral therapy fails."),
    ("Functional", "DBS for dystonia",
     "GPi outcomes in primary generalized dystonia.",
     "GPi DBS dystonia outcomes",
     "Life-changing for selected genetic/primary dystonias."),
    ("Functional", "Psychiatric neurosurgery ethics today",
     "OCD DBS evidence and consent safeguards.",
     "OCD deep brain stimulation ethics",
     "Highly regulated frontier needing PMDC-safe framing."),
    ("Functional", "Spasticity SDR in cerebral palsy",
     "Patient selection for selective dorsal rhizotomy.",
     "selective dorsal rhizotomy cerebral palsy",
     "Pediatric tone surgery improving gait potential."),
    ("Functional", "Motor cortex stimulation for pain",
     "Evidence grade for neuropathic pain MCS.",
     "motor cortex stimulation neuropathic pain",
     "Last-line option in central pain syndromes."),
    ("Functional", "Peripheral nerve stimulation advances",
     "Targeted PNS for focal neuropathic pain.",
     "peripheral nerve stimulation neuropathic pain",
     "Less invasive than CNS neuromodulation for focal pain."),
    ("Functional", "Asleep vs awake DBS techniques",
     "Imaging-guided asleep DBS accuracy evidence.",
     "asleep deep brain stimulation imaging guided",
     "Expands DBS access for patients intolerant of awake surgery."),
    ("Functional", "DBS hardware infection management",
     "Partial salvage vs full explant algorithms.",
     "DBS infection management explant",
     "Saves therapy when infections are managed protocolized."),
    ("Functional", "Epilepsy diet therapies adjunct to surgery",
     "Ketogenic strategies when surgery incomplete.",
     "ketogenic diet drug resistant epilepsy",
     "Non-surgical adjunct neurosurgeons should endorse appropriately."),
    ("Functional", "Stereo-EEG complications and yield",
     "Hemorrhage risk vs localization benefit.",
     "SEEG complications hemorrhage epilepsy",
     "Invasive monitoring consent must be precise."),
    ("Functional", "Callosotomy for drop attacks",
     "Palliative disconnection indications.",
     "corpus callosotomy drop attacks",
     "Reduces injury from atonic seizures."),
    ("Functional", "Hypothalamic hamartoma gelastic epilepsy",
     "Laser/endoscopic disconnection updates.",
     "hypothalamic hamartoma gelastic epilepsy surgery",
     "Specialized cure for a dramatic seizure type."),
    ("Functional", "Norman Dott / modern pain lesioning legacy",
     "When cordotomy/DREZ still have roles.",
     "cordotomy DREZ lesioning cancer pain",
     "Cancer pain salvage in resource-limited settings."),
    ("Functional", "Closed-loop neuromodulation future",
     "Adaptive DBS sensing research literacy.",
     "adaptive closed loop DBS sensing",
     "Next-gen devices patients will ask about."),
    ("Functional", "Tremor in MS surgical options",
     "Limited evidence and realistic expectations.",
     "multiple sclerosis tremor DBS",
     "Difficult symptom needing careful counseling."),
    ("Functional", "Facial pain differential before MVD",
     "TN vs dental vs trigeminal neuropathy red flags.",
     "trigeminal neuralgia differential diagnosis",
     "Wrong diagnosis leads to failed MVD."),
    ("Functional", "Neuromodulation clinic follow-up models",
     "Programming burden and battery management logistics.",
     "DBS programming follow-up clinic",
     "Surgery success depends on lifelong device care."),

    # ---- Pediatric (196-220) ----
    ("Pediatric", "Myelomeningocele prenatal vs postnatal repair",
     "MOMS trial legacy and fetal surgery access realities.",
     "myelomeningocele prenatal repair MOMS",
     "Changes ambulation and shunt rates when available."),
    ("Pediatric", "Chiari I decompression criteria in kids",
     "Syrinx, cough headache, and asymptomatic tonsillar ectopia.",
     "pediatric Chiari I decompression indications",
     "Stops unnecessary fossa surgery for incidental ectopia."),
    ("Pediatric", "Pediatric hydrocephalus ETV vs shunt",
     "ETVSS success score practical use.",
     "pediatric ETV vs VP shunt ETVSS",
     "First decision after diagnosing childhood hydrocephalus."),
    ("Pediatric", "Shunt infection prevention in infants",
     "Antibiotic catheters, protocol bundles, OR discipline.",
     "pediatric shunt infection prevention",
     "Infection drives huge morbidity in baby shunts."),
    ("Pediatric", "Craniosynostosis endoscopic vs open",
     "Age windows and helmet therapy adjuncts.",
     "craniosynostosis endoscopic strip craniectomy",
     "Cosmetic and ICP outcomes depend on timing."),
    ("Pediatric", "Sagittal synostosis scaphocephaly care",
     "Common single-suture pathway counseling.",
     "sagittal craniosynostosis surgery helmet",
     "Most frequent craniofacial neurosurgery pattern."),
    ("Pediatric", "Syndromic craniosynostosis airway/ICP",
     "Multidisciplinary vault expansion timing.",
     "syndromic craniosynostosis ICP airway",
     "Life-threatening ICP and airway issues beyond cosmesis."),
    ("Pediatric", "Pediatric brain tumor posterior fossa approach",
     "Vermian vs telovelar corridors and cerebellar mutism risk.",
     "pediatric posterior fossa tumor cerebellar mutism",
     "Mutism is a major QoL complication families fear."),
    ("Pediatric", "Infantile spasms neurosurgical intersections",
     "When structural lesions need epilepsy surgery early.",
     "infantile spasms focal lesion epilepsy surgery",
     "Early surgery can change developmental trajectory."),
    ("Pediatric", "Pediatric AVM hemorrhage risk",
     "Why kids' AVMs often warrant treatment.",
     "pediatric AVM hemorrhage treatment",
     "Long lifetime risk differs from adult ARUBA logic."),
    ("Pediatric", "Abusive head trauma neurosurgical role",
     "SDH patterns, OPG, and non-accidental injury pathways.",
     "abusive head trauma subdural neurosurgery",
     "Medical-legal duty of careful documentation."),
    ("Pediatric", "Neonatal IVH and posthemorrhagic hydrocephalus",
     "Temporizing devices vs early shunts.",
     "neonatal IVH posthemorrhagic hydrocephalus",
     "NICU-neurosurgery daily collaboration."),
    ("Pediatric", "Pediatric spine trauma clearance",
     "SCIWORA awareness and immobilization rules.",
     "pediatric SCIWORA spine clearance",
     "Kids can have cord injury without bony fracture."),
    ("Pediatric", "Tethered cord release indications",
     "Occult dysraphism, fatty filum, progressive deficits.",
     "tethered cord syndrome surgery indications",
     "Prevents irreversible urologic/motor decline."),
    ("Pediatric", "Encephalocele repair principles",
     "Closure, hydrocephalus surveillance, developmental outlook.",
     "encephalocele repair pediatric neurosurgery",
     "Congenital emergency with CSF and infection risks."),
    ("Pediatric", "Pediatric pituitary / sellar lesions",
     "Craniopharyngioma and Rathke cyst decision making.",
     "pediatric craniopharyngioma Rathke cyst",
     "Endocrine/vision stakes are lifelong."),
    ("Pediatric", "Moyamoya in children surgical timing",
     "Indirect bypass preference in young kids.",
     "pediatric moyamoya EDAS timing",
     "Prevents recurrent pediatric strokes."),
    ("Pediatric", "Antenatal counseling for CNS anomalies",
     "PMDC-safe, non-directive counseling frameworks.",
     "antenatal CNS anomaly counseling neurosurgery",
     "Families need accurate prognosis without coercion."),
    ("Pediatric", "Vein of Galen maladaptive management",
     "Embolization timing and heart-failure priorities.",
     "vein of Galen malformation embolization",
     "Neonatal emergency needing neurointervention networks."),
    ("Pediatric", "Pediatric chronic SDH / benign enlargement",
     "Distinguish BESS from surgical collections.",
     "benign enlargement subarachnoid spaces infant",
     "Avoids unnecessary surgery on physiologic macrocephaly."),
    ("Pediatric", "School re-entry after brain tumor",
     "Cognitive late effects and educational advocacy.",
     "pediatric brain tumor school reentry cognition",
     "Survival is not enough without learning support."),
    ("Pediatric", "Growing rod / MCGR complications neurosurgeons see",
     "Neurologic injury risk during lengthening.",
     "magnetically controlled growing rod neurologic injury",
     "Spine growth surgery can threaten the cord."),
    ("Pediatric", "Congenital dermal sinus tract infection",
     "Why tracts need excision to prevent meningitis.",
     "congenital dermal sinus tract excision",
     "Skin dimple can hide a path to the thecal sac."),
    ("Pediatric", "Pediatric ICP monitoring thresholds",
     "Age-adjusted norms and EVD strategies.",
     "pediatric ICP monitoring thresholds",
     "Adult numbers do not apply to infants."),
    ("Pediatric", "Transition of care to adult neurosurgery",
     "Spina bifida/shunt adults falling through cracks.",
     "spina bifida transition adult neurosurgery",
     "Lifelong conditions need structured handoffs."),

    # ---- Peripheral nerve (221-235) ----
    ("Peripheral nerve", "Carpal tunnel release indication refinement",
     "EDS/ultrasound grading and when to operate.",
     "carpal tunnel syndrome surgery ultrasound",
     "Highest-volume nerve surgery with big QoL impact."),
    ("Peripheral nerve", "Ulnar nerve decompression vs transposition",
     "Cubital tunnel technique selection evidence.",
     "cubital tunnel ulnar nerve transposition",
     "Second most common entrapment with technique debate."),
    ("Peripheral nerve", "Brachial plexus birth injury timing",
     "When to explore obstetric palsy.",
     "obstetric brachial plexus palsy surgery timing",
     "Early referral windows are easy to miss."),
    ("Peripheral nerve", "Adult traumatic brachial plexus repair",
     "Graft vs transfer priorities (e.g., Oberlin).",
     "traumatic brachial plexus nerve transfer",
     "Function restoration after motorcycle/trauma injuries."),
    ("Peripheral nerve", "Peroneal nerve palsy foot drop",
     "Decompression vs tendon transfer timing.",
     "common peroneal nerve palsy decompression",
     "Treatable cause of foot drop if compressive."),
    ("Peripheral nerve", "Meralgia paresthetica surgical options",
     "When to decompress lateral femoral cutaneous nerve.",
     "meralgia paresthetica nerve decompression",
     "Painful lateral thigh neuropathy after weight change/surgery."),
    ("Peripheral nerve", "Peripheral nerve sheath tumor resection",
     "Schwannoma enucleation vs NF1 MPNST red flags.",
     "peripheral nerve schwannoma MPNST NF1",
     "Wrong technique risks permanent deficit or missed malignancy."),
    ("Peripheral nerve", "Nerve transfer for spinal cord injury",
     "Emerging transfers to restore grasp after SCI.",
     "nerve transfer spinal cord injury upper limb",
     "Reconstructive hope beyond the cord lesion."),
    ("Peripheral nerve", "Iatrogenic nerve injury repair windows",
     "When to re-explore after surgical transection.",
     "iatrogenic nerve injury repair timing",
     "Ethical duty to recognize and fix OR injuries."),
    ("Peripheral nerve", "Thoracic outlet neurosurgical role",
     "True neurogenic TOS diagnosis and first rib/scalene surgery.",
     "neurogenic thoracic outlet syndrome surgery",
     "Controversial area needing strict diagnostic criteria."),
    ("Peripheral nerve", "Facial nerve reanimation after injury",
     "Grafts, transfers, and timing after CPA/parotid injury.",
     "facial nerve reanimation nerve graft",
     "Facial symmetry critical to identity and eye protection."),
    ("Peripheral nerve", "Diabetic amyotrophy vs entrapment",
     "Avoid operating on non-compressive neuropathies.",
     "diabetic radiculoplexus neuropathy vs entrapment",
     "Prevents useless surgery on inflammatory plexopathy."),
    ("Peripheral nerve", "Ultrasound-guided nerve hydrodissection",
     "Evidence grade for non-operative adjuncts.",
     "ultrasound nerve hydrodissection evidence",
     "Patients will ask; surgeons should know limits."),
    ("Peripheral nerve", "Gunshot nerve injury expectant vs early explore",
     "Ballistic nerve management algorithms.",
     "gunshot peripheral nerve injury exploration",
     "Conflict with vascular repair priorities."),
    ("Peripheral nerve", "Painful neuroma surgical strategies",
     "Relocation, targeted muscle reinnervation concepts.",
     "painful neuroma TMR surgery",
     "Improves prosthetic use and stump pain."),

    # ---- Hydrocephalus / CSF (236-255) ----
    ("Hydrocephalus / CSF", "Normal pressure hydrocephalus triage",
     "Tap test, lumbar drain trial, and shunt response predictors.",
     "normal pressure hydrocephalus tap test shunt",
     "Treatable dementia-gait mimic if carefully selected."),
    ("Hydrocephalus / CSF", "VP vs LP shunt selection",
     "When lumboperitoneal shunts fit NPH/IIH pathways.",
     "VP vs LP shunt NPH IIH",
     "Technique choice affects overdrainage and revision risk."),
    ("Hydrocephalus / CSF", "Programmable valve practical use",
     "Setting adjustments for over/underdrainage.",
     "programmable shunt valve settings overdrainage",
     "Clinic skill that prevents unnecessary revisions."),
    ("Hydrocephalus / CSF", "ETV for obstructive hydrocephalus adults",
     "Aqueduct stenosis and tumor-related success rates.",
     "endoscopic third ventriculostomy adult success",
     "Shunt-free option when anatomy allows."),
    ("Hydrocephalus / CSF", "Shunt malfunction emergency pathway",
     "Imaging + tap algorithms for the deteriorating shunted patient.",
     "shunt malfunction diagnosis CT shunt series",
     "Classic on-call emergency with herniation risk."),
    ("Hydrocephalus / CSF", "IIH surgical options when meds fail",
     "Stenting vs shunt vs optic nerve sheath fenestration.",
     "idiopathic intracranial hypertension stent shunt ONSF",
     "Vision-threatening disease with multiple surgical tools."),
    ("Hydrocephalus / CSF", "Spontaneous intracranial hypotension",
     "CSF leak localization and surgical repair tiers.",
     "spontaneous intracranial hypotension CSF leak repair",
     "Treatable cause of orthostatic headache often missed."),
    ("Hydrocephalus / CSF", "Postoperative CSF leak cranial repair",
     "Algorithm from lumbar drain to endoscopic repair.",
     "postoperative CSF leak repair endoscopic",
     "Prevents meningitis after skull-base surgery."),
    ("Hydrocephalus / CSF", "Spinal CSF leak after lumbar puncture",
     "Blood patch timing and rare surgical repairs.",
     "post LP CSF leak epidural blood patch",
     "Common iatrogenic leak with simple first-line therapy."),
    ("Hydrocephalus / CSF", "Slit ventricle syndrome",
     "Recognition and cranial expansion/valve strategies.",
     "slit ventricle syndrome shunt management",
     "Difficult chronic complication of childhood shunting."),
    ("Hydrocephalus / CSF", "Antibiotic-impregnated catheters evidence",
     "AIS vs standard catheter infection RCTs.",
     "antibiotic impregnated shunt catheter infection",
     "Device choice that may cut infection rates."),
    ("Hydrocephalus / CSF", "Choroid plexus cauterization with ETV",
     "ETV-CPC in infants evidence base.",
     "ETV choroid plexus cauterization infant",
     "Expands shunt-free success in some infants."),
    ("Hydrocephalus / CSF", "Colloid cyst sudden death risk counseling",
     "Size/location thresholds for elective removal.",
     "colloid cyst sudden death surgical indications",
     "Rare but feared mechanism families ask about."),
    ("Hydrocephalus / CSF", "Hydrocephalus after SAH/TBI EVD wean",
     "Who needs permanent shunt after acute drain.",
     "post SAH hydrocephalus shunt after EVD",
     "Daily ICU decision after vascular/trauma care."),
    ("Hydrocephalus / CSF", "MRI safety and programmable valves",
     "Reprogramming after MRI workflows.",
     "programmable shunt valve MRI reprogramming",
     "Prevents silent setting changes after scans."),
    ("Hydrocephalus / CSF", "Abdominal complications of VP shunts",
     "Pseudocyst, perforation, and hernia presentations.",
     "VP shunt abdominal pseudocyst complication",
     "Neurosurgery meets general surgery emergencies."),
    ("Hydrocephalus / CSF", "Low-pressure headache after shunt",
     "Overdrainage syndromes and antifunding strategies.",
     "shunt overdrainage low pressure headache",
     "Patients feel worse despite 'working' shunt."),
    ("Hydrocephalus / CSF", "CSF biomarkers in hydrocephalus research",
     "What is ready for clinic vs still investigational.",
     "CSF biomarkers normal pressure hydrocephalus",
     "News literacy for biomarker headlines."),
    ("Hydrocephalus / CSF", "Endoscopic septum pellucidotomy",
     "When unilateral drain fails in trapped ventricles.",
     "endoscopic septum pellucidotomy trapped ventricle",
     "Simple endoscopic fix for complex ventricular anatomy."),
    ("Hydrocephalus / CSF", "Shunt independence campaigns caution",
     "Who can safely ligate/remove childhood shunts.",
     "shunt removal independence testing",
     "Risky if done without rigorous challenge protocols."),

    # ---- Infection / inflammation (256-275) ----
    ("Infection / inflammation", "Brain abscess modern drainage + antibiotics",
     "Stereotactic aspiration vs excision evidence.",
     "brain abscess stereotactic aspiration antibiotics",
     "Curable with timely neurosurgery plus ID partnership."),
    ("Infection / inflammation", "Subdural empyema emergency",
     "Why wide drainage beats antibiotics alone.",
     "subdural empyema surgical drainage",
     "Rapidly progressive and surgically urgent."),
    ("Infection / inflammation", "Post-craniotomy bone flap infection",
     "Removal, antibiotic spacer, and delayed cranioplasty.",
     "craniotomy bone flap osteomyelitis management",
     "Common cranial infection pathway."),
    ("Infection / inflammation", "Ventriculitis diagnosis and catheter strategies",
     "CSF sampling, dual drains, and intraventricular antibiotics.",
     "ventriculitis intraventricular antibiotics",
     "Device-related infection with high morbidity."),
    ("Infection / inflammation", "Neurocysticercosis surgery indications",
     "When cysts need excision vs antiparasitics.",
     "neurocysticercosis surgery hydrocephalus",
     "Regionally important parasitic CNS disease."),
    ("Infection / inflammation", "Tuberculoma vs tumor differentiation",
     "Medical therapy first principles and biopsy triggers.",
     "CNS tuberculoma vs glioma diagnosis",
     "Avoids resecting inflammatory lesions unnecessarily."),
    ("Infection / inflammation", "Mucormycosis cranial invasion",
     "Aggressive debridement with antifungal coordination.",
     "rhino-orbito-cerebral mucormycosis surgery",
     "Post-COVID regional surge lessons still relevant."),
    ("Infection / inflammation", "Post-spine instrumentation infection biofilms",
     "Sonication and suppression therapy concepts.",
     "spinal implant infection biofilm suppression",
     "Saves hardware when appropriate."),
    ("Infection / inflammation", "Viral encephalitis neurosurgical adjuncts",
     "ICP control and biopsy in atypical cases.",
     "viral encephalitis ICP management biopsy",
     "Rare surgical roles in medical CNS infection."),
    ("Infection / inflammation", "Autoimmune encephalitis antibody era",
     "NMDA-R and when ovarian teratoma search matters.",
     "anti NMDA receptor encephalitis teratoma",
     "Neurology-neurosurgery crossover treatable psychosis mimic."),
    ("Infection / inflammation", "MOGAD and NMOSD neurosurgical pitfalls",
     "Don't operate demyelinating 'tumefactive' lesions blindly.",
     "tumefactive demyelination vs tumor biopsy",
     "Prevents devastating resections of inflammatory disease."),
    ("Infection / inflammation", "COVID-related neurovascular sequelae literacy",
     "What persists in evidence vs early speculation.",
     "COVID stroke encephalopathy long term evidence",
     "Patients still ask; answers must be evidence-tied."),
    ("Infection / inflammation", "Postoperative meningitis after skull base surgery",
     "CSF leak repair plus antimicrobial timing.",
     "postoperative meningitis skull base CSF leak",
     "Prevents catastrophic infectious complications."),
    ("Infection / inflammation", "Intramedullary abscess rare entity",
     "Recognition and drainage principles.",
     "intramedullary spinal cord abscess surgery",
     "Rare mimic of tumor with urgent ID component."),
    ("Infection / inflammation", "Hydatid disease of CNS",
     "Dowling technique and rupture avoidance.",
     "intracranial hydatid cyst Dowling technique",
     "Regional parasitology surgical classic."),
    ("Infection / inflammation", "Prion disease red flags for the surgeon",
     "Instrument handling and biopsy decisions.",
     "CJD prion precautions neurosurgery biopsy",
     "Protects OR teams and prevents futile surgery."),
    ("Infection / inflammation", "Neuro-Behçet surgical emergencies",
     "Vascular and mass-effect presentations.",
     "neuro Behcet vascular neurosurgery",
     "Systemic disease with rare neurosurgical crises."),
    ("Infection / inflammation", "Sarcoid of the CNS mass lesions",
     "Biopsy vs empiric therapy dilemmas.",
     "neurosarcoidosis mass lesion biopsy",
     "Inflammatory mimic of neoplasm."),
    ("Infection / inflammation", "Immune reconstitution inflammatory syndromes CNS",
     "IRIS after HIV therapy affecting neurosurgical plans.",
     "CNS IRIS HIV neurosurgery",
     "Timing of surgery around immune recovery."),
    ("Infection / inflammation", "Antibiotic prophylaxis in clean craniotomy",
     "Single-dose evidence and stewardship.",
     "antibiotic prophylaxis craniotomy guidelines",
     "Stops ritual prolonged antibiotics without benefit."),

    # ---- Critical care / neuromonitoring (276-295) ----
    ("Critical care", "Neuro ICU blood pressure after ICH",
     "INTERACT/ATACH targets in practical orders.",
     "ICH blood pressure target INTERACT ATACH",
     "Nursing titration that changes hematoma stability."),
    ("Critical care", "Sodium management in SAH/TBI",
     "SIADH vs CSWS diagnosis and 3% saline use.",
     "SIADH cerebral salt wasting hypertonic saline",
     "Sodium errors worsen secondary brain injury."),
    ("Critical care", "Fever control in acute brain injury",
     "Targeted temperature management evidence.",
     "fever control neurocritical care TBI stroke",
     "Simple vital sign with outsized impact."),
    ("Critical care", "Glycemic control in neuro ICU",
     "Avoiding hypoglycemia while treating stress hyperglycemia.",
     "glucose control neurocritical care",
     "Both extremes harm the injured brain."),
    ("Critical care", "Ventilation strategies protecting ICP",
     "CO2 targets and lung-protective balance.",
     "mechanical ventilation ICP PaCO2 targets",
     "Respiratory care is neuromonitoring."),
    ("Critical care", "Sedation and delirium in neurosurgery ICU",
     "Wake-up tests vs continuous sedation trade-offs.",
     "neuro ICU sedation delirium wake up test",
     "Exam quality vs comfort and ventilator sync."),
    ("Critical care", "Brain death determination standards",
     "Apnea testing and ancillary tests—legal clarity.",
     "brain death determination apnea test guidelines",
     "Ethical/legal high-stakes diagnosis."),
    ("Critical care", "Neuroprognostication after cardiac arrest",
     "Delayed multimodal prognosis to avoid nihilism.",
     "cardiac arrest neuroprognostication EEG SSEP",
     "Prevents premature withdrawal of care."),
    ("Critical care", "External ventricular drain leveling and continuum",
     "Practical EVD nursing/physician shared protocols.",
     "EVD leveling CSF drainage protocol",
     "Device safety is a team sport."),
    ("Critical care", "Continuous EEG in SAH/TBI",
     "Nonconvulsive status detection value.",
     "continuous EEG nonconvulsive status SAH TBI",
     "Hidden seizures stall recovery if missed."),
    ("Critical care", "Transcranial Doppler in SAH",
     "Vasospasm screening adjunct, not standalone.",
     "transcranial Doppler SAH vasospasm",
     "Bedside tool guiding escalation to angio."),
    ("Critical care", "Nutrition in severe TBI",
     "Early enteral feeding outcome links.",
     "nutrition severe TBI early enteral feeding",
     "Metabolic care supports neurologic recovery."),
    ("Critical care", "DVT filters in neuro ICU controversy",
     "IVC filter indications amid bleeding risk.",
     "IVC filter neurocritical care VTE",
     "Prevent PE without worsening intracranial bleed."),
    ("Critical care", "Post-craniotomy hypertension crises",
     "Pain vs Cushing vs hyperemia differentials.",
     "post craniotomy hypertension management",
     "Acute BP spikes threaten fresh hemostasis."),
    ("Critical care", "Neurogenic pulmonary edema",
     "Recognition after SAH/seizures.",
     "neurogenic pulmonary edema SAH",
     "Cardiac/pulm crossover in acute brain injury."),
    ("Critical care", "Status epilepticus ICU algorithm",
     "Benzodiazepine → ASM → anesthetic pathway.",
     "status epilepticus ICU management guidelines",
     "Minutes-to-brain damage emergency."),
    ("Critical care", "Osmotherapy mannitol vs hypertonic saline",
     "Comparative evidence and monitoring.",
     "mannitol vs hypertonic saline ICP",
     "Workhorse ICP drugs every resident must master."),
    ("Critical care", "Pupillometry automated trending",
     "Quantitative pupils as early herniation signal.",
     "automated pupillometry neurocritical care",
     "Objective exam adjunct on busy wards."),
    ("Critical care", "Family communication in neuro ICU",
     "PMDC-safe prognosis language and shared decisions.",
     "neuro ICU family communication shared decision",
     "Trust and consent quality affect every trajectory."),
    ("Critical care", "ICU liberation ABCDEF in neuro patients",
     "Adapting bundled liberation to ICP constraints.",
     "ABCDEF bundle neuro ICU adaptation",
     "Reduces delirium without unsafe mobilization."),

    # ---- Imaging / diagnostics (296-315) ----
    ("Imaging / diagnostics", "Perfusion imaging for EVT selection",
     "DAWN/DEFUSE-style imaging literacy for surgeons.",
     "CT perfusion thrombectomy selection DAWN",
     "Defines who still benefits beyond time windows."),
    ("Imaging / diagnostics", "Vessel wall MRI for vasculitis vs atherosclerosis",
     "Emerging sequences changing stroke workups.",
     "intracranial vessel wall MRI vasculitis",
     "Refines etiology when lumen imaging is ambiguous."),
    ("Imaging / diagnostics", "fMRI and DTI for preoperative planning",
     "Reliability limits surgeons must know.",
     "preoperative fMRI DTI tractography glioma",
     "Pretty maps can mislead if not validated."),
    ("Imaging / diagnostics", "FET-PET and amino-acid imaging in glioma",
     "Recurrence vs necrosis problem-solving.",
     "FET PET glioma recurrence radiation necrosis",
     "Guides reoperation decisions."),
    ("Imaging / diagnostics", "Photon-counting CT neuro applications",
     "Early evidence for temporal bone/vascular detail.",
     "photon counting CT neuroradiology",
     "Next hardware wave affecting diagnostics."),
    ("Imaging / diagnostics", "Ultra-high-field 7T MRI clinical niches",
     "Epilepsy and vascular applications emerging.",
     "7T MRI epilepsy cavernoma clinical",
     "Research-to-clinic translation patients will ask about."),
    ("Imaging / diagnostics", "Spinal diffusion tensor imaging research",
     "SCI prognosis imaging still investigational.",
     "spinal cord DTI prognosis research",
     "Separates hype from usable SCI imaging."),
    ("Imaging / diagnostics", "Contrast allergy protocols for neuro CT/MRI",
     "Premedication and alternatives for angiograms.",
     "contrast allergy premedication CTA MRI",
     "Keeps urgent vascular imaging accessible."),
    ("Imaging / diagnostics", "Incidental white matter lesions counseling",
     "Fazekas grades and when to reassure.",
     "incidental white matter lesions Fazekas",
     "Anxiety driver on routine MRI reports."),
    ("Imaging / diagnostics", "AI triage for ICH on CT",
     "FDA-cleared algorithms and false-positive realities.",
     "AI CT hemorrhage detection triage",
     "ED workflow tool, not a replacement for radiologist."),
    ("Imaging / diagnostics", "Intraoperative ultrasound elastography",
     "Research on tumor margin detection.",
     "intraoperative ultrasound elastography brain tumor",
     "Adjunct when iMRI unavailable."),
    ("Imaging / diagnostics", "Dynamic CSF flow MRI Chiari/NPH",
     "When cine CSF studies change management.",
     "CSF flow MRI Chiari NPH",
     "Supports surgical candidacy debates."),
    ("Imaging / diagnostics", "Dual-energy CT for bone/iodine separation",
     "Postop hematoma vs contrast staining.",
     "dual energy CT contrast staining vs blood",
     "Clarifies postop scans after EVT/angiography."),
    ("Imaging / diagnostics", "Quantitative pupillometry + imaging correlation",
     "Combining bedside and scan data for herniation.",
     "pupillometry CT herniation correlation",
     "Earlier detection of deterioration."),
    ("Imaging / diagnostics", "Spine EOS / low-dose alignment imaging",
     "Preop deformity planning with less radiation.",
     "EOS imaging spinal deformity radiation",
     "Safer serial imaging for scoliosis."),
    ("Imaging / diagnostics", "MR spectroscopy in brain lesions",
     "Cho/NAA patterns that support biopsy urgency.",
     "MR spectroscopy brain tumor vs abscess",
     "Helps distinguish infection from neoplasm."),
    ("Imaging / diagnostics", "Black blood MRI after flow diversion",
     "Monitoring wall healing research.",
     "black blood MRI flow diverter monitoring",
     "May refine antiplatelet duration someday."),
    ("Imaging / diagnostics", "Portable MRI in neuro ICU",
     "Feasibility and use-cases for low-field scanners.",
     "portable MRI neuro ICU feasibility",
     "Brings imaging to unstable patients."),
    ("Imaging / diagnostics", "Radiomics in meningioma / glioma research",
     "What radiomics can and cannot claim yet.",
     "radiomics meningioma glioma prediction",
     "News literacy against overclaimed AI papers."),
    ("Imaging / diagnostics", "Screening MRI in asymptomatic athletes ethical angle",
     "Incidentaloma cascade risks.",
     "screening brain MRI athletes incidental findings",
     "Prevention theater can create surgical harm."),

    # ---- Neuro-oncology medical therapies (316-330) ----
    ("Neuro-oncology medical", "Temozolomide and MGMT in GBM care",
     "Stupp era essentials surgeons must reinforce postop.",
     "temozolomide MGMT glioblastoma Stupp",
     "Surgery is only the start of GBM therapy."),
    ("Neuro-oncology medical", "Tumor treating fields real-world adherence",
     "EF-14 legacy and practical wear-time counseling.",
     "tumor treating fields Optune adherence GBM",
     "Device therapy patients ask about after resection."),
    ("Neuro-oncology medical", "IDH inhibitors in glioma",
     "Vorasidenib/INEOIGUE-type evidence for surgeons' MDTs.",
     "vorasidenib IDH inhibitor glioma",
     "May delay radiation in selected low-grade disease."),
    ("Neuro-oncology medical", "BRAF/MEK targeted therapy in CNS tumors",
     "Who needs molecular testing after resection.",
     "BRAF MEK inhibitor brain tumor",
     "Tissue handling affects targeted options."),
    ("Neuro-oncology medical", "Checkpoint inhibitors in brain mets / GBM limits",
     "Where immunotherapy helps and where it disappoints.",
     "checkpoint inhibitor brain metastasis glioblastoma",
     "Sets realistic expectations after viral headlines."),
    ("Neuro-oncology medical", "Bevacizumab for recurrent GBM / radiation necrosis",
     "Steroid-sparing roles and surgical timing.",
     "bevacizumab recurrent GBM radiation necrosis",
     "Common salvage affecting wound healing if reoperating."),
    ("Neuro-oncology medical", "PCNSL methotrexate regimens and surgery limits",
     "Why resection is usually not the therapy.",
     "PCNSL high dose methotrexate",
     "Keeps neurosurgeons in diagnostic not cytoreductive role."),
    ("Neuro-oncology medical", "Medulloblastoma molecular therapy frontiers",
     "SHH/WNT group implications beyond surgery.",
     "medulloblastoma SHH WNT targeted therapy",
     "Residual disease and subgroup drive adjuvant intensity."),
    ("Neuro-oncology medical", "Meningioma somatostatin receptor theranostics",
     "Lutathera-style research for refractory meningioma.",
     "meningioma SSTR radionuclide therapy",
     "Option space for unresectable progressive disease."),
    ("Neuro-oncology medical", "Proton therapy for CNS tumors indications",
     "When protons reduce cognitive/endocrine toxicity.",
     "proton therapy brain tumor pediatrics",
     "Referral knowledge for young and eloquent cases."),
    ("Neuro-oncology medical", "CAR-T in CNS malignancy research status",
     "Honest brief on trial stage vs clinical readiness.",
     "CAR-T glioblastoma clinical trial",
     "Patients bring headlines; clinicians need sober framing."),
    ("Neuro-oncology medical", "Oncolytic virus therapy neurosurgical delivery",
     "Convection-enhanced delivery research literacy.",
     "oncolytic virus glioblastoma convection enhanced delivery",
     "OR may deliver future biologics."),
    ("Neuro-oncology medical", "Seizure meds interacting with chemo/TKIs",
     "Enzyme-inducing AED pitfalls.",
     "enzyme inducing antiepileptic chemotherapy interaction",
     "Drug interactions undermine both seizure and tumor control."),
    ("Neuro-oncology medical", "Fertility preservation before cranial RT/chemo",
     "Young adult counseling checklist.",
     "fertility preservation brain tumor therapy",
     "Survivorship starts at diagnosis."),
    ("Neuro-oncology medical", "Palliative care concurrent with neuro-oncology",
     "Early palliative integration outcome data.",
     "early palliative care glioblastoma outcomes",
     "Improves QoL without shortening appropriate therapy."),

    # ---- Rehabilitation / outcomes (331-345) ----
    ("Rehabilitation / outcomes", "Early physiatry after stroke and TBI",
     "Dose and timing of rehab that change mRS.",
     "early rehabilitation stroke TBI intensity",
     "Surgery success unrealized without rehab."),
    ("Rehabilitation / outcomes", "Constraint-induced movement therapy",
     "Evidence for upper-limb recovery post-stroke.",
     "constraint induced movement therapy stroke",
     "Practical therapy patients can pursue."),
    ("Rehabilitation / outcomes", "Cognitive rehab after aneurysmal SAH",
     "Return-to-work cognitive domains.",
     "cognitive rehabilitation after SAH",
     "Hidden disability after 'successful' aneurysm treatment."),
    ("Rehabilitation / outcomes", "Sphincter rehab after cauda equina",
     "Urology-physiatry pathway postop.",
     "cauda equina bladder rehabilitation",
     "Dignity outcomes beyond walking."),
    ("Rehabilitation / outcomes", "Robotic gait training after SCI",
     "Evidence grade vs conventional Lokomat-style therapy.",
     "robotic gait training spinal cord injury",
     "Technology patients request after SCI."),
    ("Rehabilitation / outcomes", "Vestibular rehab after vestibular schwannoma",
     "Compensation training post-resection/SRS.",
     "vestibular rehabilitation after schwannoma",
     "Balance recovery is trainable."),
    ("Rehabilitation / outcomes", "Speech therapy after awake glioma surgery",
     "Early SLP protocols for dysphasia.",
     "speech therapy after awake craniotomy",
     "Language gains need structured therapy."),
    ("Rehabilitation / outcomes", "PROMs in spine surgery",
     "ODI/NDI/EQ-5D as outcome truth serum.",
     "patient reported outcomes spine surgery ODI",
     "Moves practice beyond surgeon-rated 'success'."),
    ("Rehabilitation / outcomes", "Return to driving after craniotomy/seizure",
     "Jurisdiction-aware counseling principles (Pakistan context).",
     "return to driving after craniotomy seizure",
     "Safety and livelihood counseling."),
    ("Rehabilitation / outcomes", "Caregiver burden after severe TBI",
     "Support resources as part of discharge planning.",
     "caregiver burden traumatic brain injury",
     "Family health determines patient trajectory."),
    ("Rehabilitation / outcomes", "Vocational rehab after mild-moderate TBI",
     "Invisible deficits blocking employment.",
     "vocational rehabilitation mild TBI",
     "Economic recovery is a clinical outcome."),
    ("Rehabilitation / outcomes", "Spasticity management ladder postop/SCI",
     "From PT to baclofen pump staging.",
     "spasticity management spinal cord injury",
     "Tone control enables further rehab gains."),
    ("Rehabilitation / outcomes", "Neurogenic bladder permanent options",
     "When intermittent cath fails—surgical urinary diversion literacy.",
     "neurogenic bladder surgical options SCI",
     "Infection and kidney protection long-term."),
    ("Rehabilitation / outcomes", "Quality of life after vestibular schwannoma pathways",
     "Compare observation/SRS/surgery QoL data.",
     "quality of life vestibular schwannoma treatment",
     "Hearing/facial outcomes drive treatment choice."),
    ("Rehabilitation / outcomes", "Long-term surveillance fatigue in tumor survivors",
     "Scanxiety and sustainable follow-up schedules.",
     "cancer scanxiety brain tumor surveillance",
     "Survivorship psychology is part of neurosurgical care."),

    # ---- Ethics / guidelines / communication (346-365) ----
    ("Ethics / guidelines", "Informed consent for elective neurosurgery",
     "Risk communication standards without fear or sugarcoating.",
     "informed consent neurosurgery shared decision",
     "Ethical and medicolegal foundation of elective care."),
    ("Ethics / guidelines", "Second opinion culture in brain tumors",
     "How to encourage without abandoning patients.",
     "second opinion brain tumor ethics",
     "Complex disease benefits from another trained mind."),
    ("Ethics / guidelines", "Goals of care after devastating ICH/TBI",
     "Time-limited trials vs early palliation framing.",
     "goals of care ICH TBI palliative neurosurgery",
     "Prevents both premature and prolonged non-beneficial care."),
    ("Ethics / guidelines", "Surgical tourism risks in spine/neuromodulation",
     "Counseling patients considering overseas procedures.",
     "medical tourism spine surgery risks",
     "Complication ownership often returns home."),
    ("Ethics / guidelines", "Conflicts of interest in device-heavy spine care",
     "Transparency around implants and industry ties.",
     "conflict of interest spinal implants ethics",
     "Trust requires disclosure."),
    ("Ethics / guidelines", "Pediatric assent alongside parental consent",
     "Age-appropriate involvement in surgical decisions.",
     "pediatric assent neurosurgery ethics",
     "Respects emerging autonomy in children."),
    ("Ethics / guidelines", "Research consent for intraoperative tissue banking",
     "Separating clinical care from biobank research clearly.",
     "biobank consent brain tumor research ethics",
     "PMDC-aligned research integrity."),
    ("Ethics / guidelines", "Social media medical advice boundaries",
     "What neurosurgeons may say publicly without diagnosing.",
     "physician social media ethics neurosurgery",
     "Protects public and license."),
    ("Ethics / guidelines", "Guideline literacy: AANS/CNS vs local adaptation",
     "How to adapt high-income guidelines to Pakistani resources.",
     "AANS CNS guidelines low resource adaptation",
     "Evidence must meet local reality."),
    ("Ethics / guidelines", "Antimicrobial stewardship in neurosurgery",
     "Duration limits after clean cases.",
     "antimicrobial stewardship neurosurgery",
     "Resistance is a patient-safety issue."),
    ("Ethics / guidelines", "Disclosure of intraoperative complications",
     "Honest communication after adverse events.",
     "disclosure medical error neurosurgery ethics",
     "Maintains trust and enables timely rescue care."),
    ("Ethics / guidelines", "Capacity assessment before high-risk surgery",
     "When psychiatric/neurologic disease affects consent.",
     "decision making capacity neurosurgery consent",
     "Invalid consent is unethical and unsafe."),
    ("Ethics / guidelines", "Equity in EVT and aneurysm care access",
     "Geographic and economic barriers in stroke nets.",
     "stroke care access equity thrombectomy",
     "Outcome gaps are system ethics issues."),
    ("Ethics / guidelines", "Do-not-escalate orders in neuro ICU clarity",
     "Writing actionable limitations of therapy.",
     "DNR DNE neuro ICU documentation",
     "Ambiguous orders harm teams and families."),
    ("Ethics / guidelines", "Trainee autonomy graded responsibility",
     "Safe teaching OR without patient sacrifice.",
     "neurosurgery training autonomy patient safety",
     "Future workforce depends on ethical teaching."),
    ("Ethics / guidelines", "Religious and cultural end-of-life sensitivities",
     "Pakistan-context respectful neuroprognosis talks.",
     "end of life cultural sensitivity Pakistan neurosurgery",
     "Care must fit family values without abandoning truth."),
    ("Ethics / guidelines", "Incidental genetic findings in tumor NGS",
     "What to tell patients about germline hits.",
     "germline findings brain tumor sequencing ethics",
     "Molecular tests can reveal family cancer risk."),
    ("Ethics / guidelines", "Industry-sponsored trial enrollment counseling",
     "Equipoise and patient-first framing.",
     "clinical trial enrollment counseling neurosurgery",
     "Research offers access but must not coerce."),
    ("Ethics / guidelines", "Documentation standards for medicolegal resilience",
     "What operative notes must capture after complications.",
     "operative note documentation medicolegal neurosurgery",
     "Good notes protect patients and truthful defense."),
    ("Ethics / guidelines", "One-topic daily public education ethics",
     "Why single accurate daily briefs beat content floods.",
     "health communication ethics daily medical education",
     "Trust grows from consistent, non-sensational teaching."),
]


def assert_seed_count() -> None:
    if len(SEEDS) != 365:
        raise SystemExit(f"Expected 365 seeds, got {len(SEEDS)}")


def build_entries() -> list[dict]:
    assert_seed_count()
    entries = []
    for i, (domain, topic, news_angle, keywords, relevance) in enumerate(SEEDS, start=1):
        d = ANCHOR_DATE + timedelta(days=i - 1)
        entries.append(
            {
                "day": i,
                "date": d.isoformat(),
                "topic": topic,
                "domain": domain,
                "news_angle": news_angle,
                "search_keywords": keywords,
                "practice_relevance": relevance,
                "uploads_per_day": 1,
                "grok_authenticated": False,
            }
        )
    return entries


def domain_counts(entries: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for e in entries:
        counts[e["domain"]] = counts.get(e["domain"], 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))


def write_seed(path: Path) -> dict:
    entries = build_entries()
    payload = {
        "calendar_id": CALENDAR_ID,
        "version": 1,
        "dating": {
            "day_1": ANCHOR_DATE.isoformat(),
            "day_365": (ANCHOR_DATE + timedelta(days=364)).isoformat(),
            "timezone_note": "Calendar dates are civil dates for Asia/Karachi (PKT). Day index ignores DST.",
            "rule": DATING_NOTE,
            "uploads_per_day": 1,
            "selection_rule": (
                "For date D, day_index = (D - 2026-10-02).days + 1. "
                "Publish exactly ONE research digest for that single topic."
            ),
        },
        "counts_by_domain": domain_counts(entries),
        "total_topics": len(entries),
        "topics": entries,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return payload


if __name__ == "__main__":
    out = Path(__file__).resolve().parent / "council_output" / "neurosurgery_365_calendar.seed.json"
    payload = write_seed(out)
    print(f"Wrote {out} ({payload['total_topics']} topics)")
    print("Domain counts:")
    for k, v in payload["counts_by_domain"].items():
        print(f"  {k}: {v}")
